# Config file for automatic testing at travis-ci.org
language: python

# install gcc 4.8 for cxx11
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 gcc-4.8
  - sudo ln -sf /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo ln -sf /usr/bin/g++-4.8 /usr/bin/g++
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

python:
- "3.4"
- "3.3"
- "2.7"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy pip
  - pip install coveralls
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: coverage run --source hope setup.py test
after_success:
    coveralls
