# Config file for automatic testing at travis-ci.org
language: python

# install gcc 4.8 for cxx11
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 gcc-4.8
  - sudo ln -sf /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo ln -sf /usr/bin/g++-4.8 /usr/bin/g++

python:
- "3.4"
- "3.3"
- "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# Note: we only use coveralls with Travis, not tox. pip install coveralls doesn't work on Windows.
# This setup makes it possible for:
# 1. the tests to be run with tox on Windows
# 2. Windows users to use the requirements files without running into installation problems.
install:
- pip install coveralls
- pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: coverage run --source hope setup.py test
after_success:
    coveralls
